version: "1"
services:

  model_nasa_rwanda_field_boundary_competition_silver_v1:
    image: radiantearth/model_nasa_rwanda_field_boundary_competition_silver:1
    volumes:
      - "${INPUT_DATA}:/opt/radiant/data/input"
      - "${OUTPUT_DATA}:/opt/radiant/data/output"
      - "${MODELS_DIR}:/opt/radiant/models"
      - "${WORKSPACE_DIR}:/opt/radiant/workspace"
    environment:
      - INPUT_DATA=/opt/radiant/data/input
      - OUTPUT_DATA=/opt/radiant/data/output
      - MODELS_DIR=/opt/radiant/models
      - WORKSPACE_DIR=/opt/radiant/workspace
